import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, Check, ChevronDown, CircleHelp, Clock3, Copy, LogOut, MessageCircle, RotateCcw, Send, ShieldAlert, Trophy, Users, WifiOff, X, Zap } from "lucide-react";
import { useArenaSocket } from "@/hooks/useSocket";
import { useGameStore } from "@/store/gameStore";
import { TOPICS, type PublicQuestion, type TopicId } from "../../../shared/domain";
import type { MatchPublicState } from "@/types";

const codeOf = (value: string) => value.toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 6);
export default function Room() {
  const { id } = useParams();
  const roomId = codeOf(id ?? "");
  const navigate = useNavigate();
  const name = useGameStore((state) => state.playerName);
  const room = useGameStore((state) => state.room);
  const match = useGameStore((state) => state.match);
  const seatId = useGameStore((state) => state.seatId);
  const clearSession = useGameStore((state) => state.clearSession);
  const api = useArenaSocket(roomId, name);
  const questionId = match?.question?.id ?? null;
  const [chatOpen, setChatOpen] = useState(false);
  const [chatText, setChatText] = useState("");
  const [answerState, setAnswerState] = useState<{ questionId: string | null; value: string | number | string[] }>({ questionId: null, value: "" });
  const [orderedState, setOrderedState] = useState<{ questionId: string | null; value: string[] }>({ questionId: null, value: [] });
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [selectedTopics, setSelectedTopics] = useState<TopicId[]>(["arrays-memory", "linked-lists", "stacks", "queues", "binary-trees", "sorting", "recursion", "analysis-mathematics"]);
  const [timer, setTimer] = useState(90);
  const [copied, setCopied] = useState(false);
  const [now, setNow] = useState(() => Date.now());
  const answer = answerState.questionId === questionId ? answerState.value : "";
  const ordered = orderedState.questionId === questionId ? orderedState.value : [];
  const setAnswer = (value: string | number | string[]) => setAnswerState({ questionId, value });
  const setOrdered = (value: string[]) => setOrderedState({ questionId, value });

  useEffect(() => { if (!name || !roomId) navigate("/", { replace: true }); }, [name, navigate, roomId]);
  useEffect(() => { const id = window.setInterval(() => setNow(Date.now()), 250); return () => window.clearInterval(id); }, []);
  const seats = room?.seats ?? [];
  const self = seats.find((seat) => seat.seatId === seatId);
  const opponent = seats.find((seat) => seat.seatId !== seatId);
  const host = room?.metadata.hostSeatId === seatId;
  const isSubmitted = seatId ? Boolean(match?.submissions[seatId]?.submitted) : false;
  const seconds = match?.phase === "COUNTDOWN" ? Math.max(0, Math.ceil(((match.countdownEndsAt ?? now) - now) / 1000)) : match?.questionEndsAt ? Math.max(0, Math.ceil((match.questionEndsAt - now) / 1000)) : null;
  const configure = () => { if (selectedTopics.length) { api.clearSubmission(); api.configure({ topicIds: selectedTopics, roundCount: 5, questionTimerSeconds: timer }); } setSettingsOpen(false); };
  const leave = () => { if (window.confirm(match && ["COUNTDOWN", "QUESTION", "REVEAL", "PAUSED"].includes(match.phase) ? "Leave and forfeit this match? Your opponent will win." : "Leave this room?")) { api.leave(); clearSession(); navigate("/", { replace: true }); } };
  const sendChat = (event: React.FormEvent) => { event.preventDefault(); if (!chatText.trim()) return; api.sendChat(chatText); setChatText(""); };
  const copy = async () => { try { await navigator.clipboard.writeText(roomId); setCopied(true); setTimeout(() => setCopied(false), 1200); } catch { /* clipboard is optional */ } };
  const submit = () => { if (!match?.question || isSubmitted || match.phase !== "QUESTION") return; const value = match.question.type === "ordered-sequence" ? ordered : answer; api.clearSubmission(); api.submit({ questionId: match.question.id, answer: value }); };

  if (!name || !roomId) return null;
  return <div className="min-h-screen bg-ink text-cream"><header className="sticky top-0 z-30 border-b border-line bg-ink/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center gap-4 px-4 sm:px-8"><button className="icon-button" onClick={leave} aria-label="Leave room"><ArrowLeft size={17} /></button><div className="min-w-0 flex-1"><p className="eyebrow">{match ? phaseLabel(match.phase) : "connecting"} · {match?.source === "public" ? "public queue" : "private 1v1"}</p><p className="truncate font-mono text-sm text-muted">{self?.name ?? name} <span className="text-line">vs</span> {opponent?.name ?? "open seat"}</p></div><button className="code-pill" onClick={copy}><span>{roomId}</span>{copied ? <Check size={14} /> : <Copy size={14} />}</button><button className="icon-button relative" onClick={() => setChatOpen((open) => !open)} aria-label="Toggle chat"><MessageCircle size={17} />{api.messages.length > 0 && <span className="badge">{Math.min(99, api.messages.length)}</span>}</button><button className="button button-danger hidden sm:flex" onClick={leave}><LogOut size={14} /> leave</button></div></header>
    {api.connection !== "connected" && !match?.pause && <div className="border-b border-gold/20 bg-gold/10 px-4 py-2 text-center font-mono text-xs text-gold"><WifiOff className="mr-2 inline" size={14} />reconnecting to the server…</div>}
    <main className="mx-auto max-w-7xl px-4 py-6 sm:px-8 sm:py-10">{api.errorNotice && <div className="notice-error mb-5"><ShieldAlert size={16} />{api.errorNotice}</div>}{!match ? <Loading /> : match.phase === "LOBBY" || match.phase === "SETUP" || match.phase === "READY" || match.phase === "REMATCH" ? <Lobby match={match} seatId={seatId} host={host} self={self?.name ?? name} opponent={opponent?.name} selectedTopics={selectedTopics} timer={timer} setSelectedTopics={setSelectedTopics} setTimer={setTimer} settingsOpen={settingsOpen} setSettingsOpen={setSettingsOpen} onConfigure={configure} onReady={api.ready} /> : match.phase === "COUNTDOWN" ? <Countdown seconds={seconds ?? 3} round={match.roundIndex + 1} /> : match.phase === "QUESTION" ? <QuestionStage match={match} seatId={seatId} opponent={opponent?.name} seconds={seconds} answer={answer} setAnswer={setAnswer} ordered={ordered} setOrdered={setOrdered} submitted={isSubmitted} submit={submit} lastSubmission={isSubmitted ? api.lastSubmission : false} /> : match.phase === "REVEAL" ? <Reveal match={match} /> : match.phase === "PAUSED" ? <Paused pause={match.pause} now={now} /> : <Results match={match} selfSeatId={seatId} onRematch={api.rematch} onHome={leave} />}</main>
    <Chat open={chatOpen} messages={api.messages} value={chatText} setValue={setChatText} onClose={() => setChatOpen(false)} onSend={sendChat} self={self?.name ?? name} />
  </div>;
}

const Lobby = ({ match, seatId, host, self, opponent, selectedTopics, timer, setSelectedTopics, setTimer, settingsOpen, setSettingsOpen, onConfigure, onReady }: { match: MatchPublicState; seatId: string | null; host: boolean; self: string; opponent?: string; selectedTopics: TopicId[]; timer: number; setSelectedTopics: (topics: TopicId[]) => void; setTimer: (timer: number) => void; settingsOpen: boolean; setSettingsOpen: (open: boolean) => void; onConfigure: () => void; onReady: () => void }) => <section className="mx-auto max-w-5xl py-6 sm:py-14"><div className="text-center"><p className="eyebrow text-gold">{match.phase === "REMATCH" ? "new round" : "room lobby"}</p><h1 className="display mt-3 text-5xl sm:text-7xl">lock in.</h1><p className="mx-auto mt-4 max-w-lg text-muted">Both guests ready up when the pool and timer feel right. Five rounds. One server clock.</p><button className="code-pill mx-auto mt-6" onClick={() => navigator.clipboard.writeText(match.roomId)}>{match.roomId} <Copy size={14} /></button></div><div className="mt-10 grid gap-4 sm:grid-cols-2"><SeatCard label="you" name={self} ready={Boolean(seatId && match.ready[seatId])} /><SeatCard label="opponent" name={opponent ?? "waiting for a guest"} ready={Boolean(opponent && Object.entries(match.ready).find(([id]) => id !== seatId)?.[1])} empty={!opponent} /></div>{host && <div className="panel mt-5 p-5"><button className="flex w-full items-center justify-between text-left" onClick={() => setSettingsOpen(!settingsOpen)}><span><span className="eyebrow text-gold">host controls</span><span className="mt-1 block font-semibold">{selectedTopics.length} topics · {timer}s per question</span></span><ChevronDown className={settingsOpen ? "rotate-180 text-gold" : "text-muted"} size={17} /></button>{settingsOpen && <div className="mt-5 border-t border-line pt-5"><div className="grid gap-2 sm:grid-cols-2">{TOPICS.map((topic) => <button key={topic.id} className={`topic-chip ${selectedTopics.includes(topic.id) ? "topic-chip-active" : ""}`} onClick={() => setSelectedTopics(selectedTopics.includes(topic.id) ? selectedTopics.filter((item) => item !== topic.id) : [...selectedTopics, topic.id])}>{topic.label}{selectedTopics.includes(topic.id) && <Check size={14} />}</button>)}</div><div className="mt-4 flex items-center gap-3"><span className="text-sm text-muted">Timer</span><select className="field w-auto" value={timer} onChange={(event) => setTimer(Number(event.target.value))}><option value={60}>60 sec</option><option value={90}>90 sec</option><option value={120}>120 sec</option><option value={300}>5 min</option></select><button className="button button-primary ml-auto" onClick={onConfigure}>save settings</button></div></div>}</div>}<button className="button button-primary mx-auto mt-7 flex min-w-64" disabled={!opponent} onClick={onReady}><Check size={16} /> {seatId && match.ready[seatId] ? "unready" : "ready up"}</button></section>;

const SeatCard = ({ label, name, ready, empty }: { label: string; name: string; ready: boolean; empty?: boolean }) => <article className={`panel p-6 ${empty ? "border-dashed" : ""}`}><div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-full border border-line bg-ink text-gold"><Users size={19} /></span><span className={`status-pill ${ready ? "status-good" : ""}`}>{ready ? "ready" : empty ? "open seat" : "not ready"}</span></div><p className="eyebrow mt-8">{label}</p><p className={`mt-2 text-xl font-semibold ${empty ? "text-muted" : ""}`}>{name}</p></article>;

const Countdown = ({ seconds, round }: { seconds: number; round: number }) => <section className="mx-auto flex min-h-[65vh] max-w-xl flex-col items-center justify-center text-center"><p className="eyebrow text-gold">round {round} of 5</p><p className="display mt-4 text-[9rem] leading-none text-gold">{seconds}</p><p className="mt-5 text-muted">Get your scratch paper ready. The next prompt is coming.</p></section>;

const QuestionStage = ({ match, seatId, opponent, seconds, answer, setAnswer, ordered, setOrdered, submitted, submit, lastSubmission }: { match: MatchPublicState; seatId: string | null; opponent?: string; seconds: number | null; answer: string | number | string[]; setAnswer: (answer: string | number | string[]) => void; ordered: string[]; setOrdered: (items: string[]) => void; submitted: boolean; submit: () => void; lastSubmission: boolean }) => { const question = match.question; if (!question) return null; const opponentSeat = Object.keys(match.submissions).find((id) => id !== seatId); const opponentSubmitted = opponentSeat ? match.submissions[opponentSeat]?.submitted : false; return <section className="mx-auto max-w-4xl py-3 sm:py-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow text-gold">question {match.roundIndex + 1} / {match.totalRounds}</p><p className="mt-1 text-sm text-muted">{topicName(question.topicId)} · {question.difficulty}</p></div><div className={`timer ${seconds !== null && seconds <= 10 ? "timer-hot" : ""}`}><Clock3 size={16} />{seconds ?? "--"}s</div></div><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_18rem]"><article className="panel p-6 sm:p-9"><div className="flex items-start justify-between gap-5"><h1 className="text-2xl font-semibold leading-snug sm:text-4xl">{question.prompt}</h1><span className="type-pill">{typeLabel(question.type)}</span></div><AnswerControl question={question} answer={answer} setAnswer={setAnswer} ordered={ordered} setOrdered={setOrdered} disabled={submitted} /><button className="button button-primary mt-8 w-full" disabled={submitted || !hasAnswer(question, answer, ordered)} onClick={submit}>{submitted ? <><Check size={16} /> answer locked</> : <><Zap size={16} /> submit answer</>}</button>{lastSubmission && <p className="mt-4 text-center text-sm text-muted" role="status">Server received and locked your answer. Correctness appears at reveal.</p>}</article><aside className="space-y-3"><MiniScore label="you" name="your score" score={seatId ? match.scores[seatId]?.total ?? 0 : 0} submitted={submitted} /><MiniScore label="opponent" name={opponent ?? "opponent"} score={opponentSeat ? match.scores[opponentSeat]?.total ?? 0 : 0} submitted={opponentSubmitted} /><div className="notice-info"><CircleHelp size={16} /><p>Correctness is worth <strong>1,000</strong>. Speed can add up to 300.</p></div></aside></div></section>; };

const AnswerControl = ({ question, answer, setAnswer, ordered, setOrdered, disabled }: { question: PublicQuestion; answer: string | number | string[]; setAnswer: (answer: string | number | string[]) => void; ordered: string[]; setOrdered: (items: string[]) => void; disabled: boolean }) => { if (question.type === "multiple-choice") return <div className="mt-9 grid gap-3">{question.options?.map((option) => <button key={option.id} disabled={disabled} className={`answer-option ${answer === option.id ? "answer-option-active" : ""}`} onClick={() => setAnswer(option.id)}><span className="option-key">{option.id}</span><span>{option.label}</span></button>)}</div>; if (question.type === "ordered-sequence") return <div className="mt-9"><p className="field-label">tap items in order</p><div className="mt-3 grid gap-2">{question.items?.map((item) => <button key={item.id} disabled={disabled || ordered.includes(item.id)} className={`answer-option ${ordered.includes(item.id) ? "opacity-40" : ""}`} onClick={() => setOrdered([...ordered, item.id])}><span className="option-key">{ordered.indexOf(item.id) + 1 || "·"}</span>{item.label}</button>)}</div>{ordered.length > 0 && <button className="mt-3 text-xs text-muted underline" onClick={() => setOrdered([])}>reset order</button>}</div>; if (question.type === "code-output") return <textarea disabled={disabled} className="field mt-9 min-h-32 font-mono" value={typeof answer === "string" ? answer : ""} onChange={(event) => setAnswer(event.target.value)} placeholder="write the output, one line at a time" />; return <input disabled={disabled} type={question.type === "numeric" ? "number" : "text"} className="field mt-9 text-lg" value={typeof answer === "string" || typeof answer === "number" ? answer : ""} onChange={(event) => setAnswer(question.type === "numeric" ? event.target.value : event.target.value)} placeholder={question.unit ? `answer in ${question.unit}` : "type your answer"} />; };
const hasAnswer = (question: PublicQuestion, answer: string | number | string[], ordered: string[]) => question.type === "ordered-sequence" ? ordered.length === (question.orderLength ?? question.items?.length ?? 0) : String(answer).trim().length > 0;
const MiniScore = ({ label, name, score, submitted }: { label: string; name: string; score: number; submitted: boolean }) => <div className="panel p-4"><div className="flex items-center justify-between"><span className="eyebrow">{label}</span>{submitted && <Check className="text-green-300" size={15} />}</div><p className="mt-2 truncate text-sm text-muted">{name}</p><p className="mt-2 font-mono text-xl text-gold">{score.toLocaleString()}</p></div>;

const Reveal = ({ match }: { match: MatchPublicState }) => <section className="mx-auto flex min-h-[65vh] max-w-2xl flex-col justify-center text-center"><p className="eyebrow text-gold">round reveal · {match.history.at(-1)?.round ?? match.roundIndex + 1}</p><h1 className="display mt-3 text-5xl">the answer was</h1><div className="panel mt-8 p-7 text-left"><p className="text-2xl font-semibold text-gold">{match.revealedQuestion ? formatAnswer(match.revealedQuestion.answer) : "Answer unavailable"}</p><p className="mt-5 leading-7 text-muted">{match.revealedQuestion?.explanation}</p><p className="mt-4 text-xs text-muted">Assumptions: {match.revealedQuestion?.assumptions.join(" · ")}</p></div><p className="mt-7 text-sm text-muted">Next round is loading…</p></section>;

const Paused = ({ pause, now }: { pause: MatchPublicState["pause"]; now: number }) => <section className="mx-auto flex min-h-[65vh] max-w-xl flex-col items-center justify-center text-center"><WifiOff className="text-gold" size={34} /><p className="eyebrow mt-6 text-gold">match paused</p><h1 className="display mt-3 text-4xl">waiting for {pause?.seatName ?? "a guest"}</h1><p className="mt-4 text-muted">Both players are paused. Timers resume only when the guest reconnects.</p><p className="mt-7 font-mono text-2xl text-gold">{pause ? Math.max(0, Math.ceil((pause.expiresAt - now) / 1000)) : 0}s</p></section>;

const Results = ({ match, selfSeatId, onRematch, onHome }: { match: MatchPublicState; selfSeatId: string | null; onRematch: () => void; onHome: () => void }) => { const winner = match.winnerSeatId; const won = winner === selfSeatId; return <section className="mx-auto max-w-4xl py-6 sm:py-12"><div className="text-center"><Trophy className="mx-auto text-gold" size={34} /><p className="eyebrow mt-6 text-gold">{match.endReason === "completed" ? "five-round results" : "match outcome"}</p><h1 className="display mt-3 text-6xl">{winner ? won ? "you win" : "good fight" : "draw"}</h1><p className="mt-4 text-muted">Correctness leads. Speed breaks ties only after correct answers are counted.</p></div><div className="mt-10 grid gap-3 sm:grid-cols-2">{Object.entries(match.scores).map(([id, score]) => <article key={id} className={`panel p-5 ${id === selfSeatId ? "border-gold/50" : ""}`}><p className="eyebrow">{id === selfSeatId ? "you" : "opponent"}</p><p className="mt-2 font-mono text-3xl text-gold">{score.total.toLocaleString()}</p><p className="mt-2 text-sm text-muted">{score.correct} correct · {score.responseMs ? `${(score.responseMs / 1000).toFixed(1)}s response time` : "no responses"}</p></article>)}</div><div className="mt-8 flex flex-wrap justify-center gap-3"><button className="button button-primary" onClick={onRematch}><RotateCcw size={16} /> rematch</button><button className="button button-ghost" onClick={onHome}><LogOut size={16} /> leave room</button></div><div className="mt-10 space-y-2"><p className="eyebrow">round review</p>{match.history.map((round) => <details key={round.round} className="panel group p-4"><summary className="flex cursor-pointer list-none items-center justify-between"><span><span className="eyebrow">round {round.round}</span><span className="ml-4 font-medium">{round.question.prompt}</span></span><ChevronDown className="group-open:rotate-180" size={16} /></summary><div className="mt-4 border-t border-line pt-4 text-sm"><p className="text-gold">Answer: {formatAnswer(round.question.answer)}</p><p className="mt-2 text-muted">{round.question.explanation}</p><p className="mt-3 text-xs text-muted">Assumptions: {round.question.assumptions.join(" · ")}</p></div></details>)}</div></section>; };
const formatAnswer = (answer: string | number | string[]) => Array.isArray(answer) ? answer.join(" → ") : String(answer);
const Chat = ({ open, messages, value, setValue, onClose, onSend, self }: { open: boolean; messages: Array<{ id: string; type: "system" | "user"; sender: string; text: string }>; value: string; setValue: (value: string) => void; onClose: () => void; onSend: (event: React.FormEvent) => void; self: string }) => <aside className={`fixed bottom-0 right-0 top-16 z-40 flex w-[min(24rem,94vw)] flex-col border-l border-line bg-panel shadow-2xl transition-transform ${open ? "translate-x-0" : "translate-x-full"}`}><div className="flex items-center justify-between border-b border-line p-5"><div><p className="eyebrow text-gold">secondary channel</p><h2 className="font-semibold">room chat</h2></div><button className="icon-button" onClick={onClose} aria-label="Close chat"><X size={16} /></button></div><div className="flex-1 space-y-3 overflow-y-auto p-4">{messages.length === 0 ? <p className="mt-8 text-center text-sm text-muted">No messages yet.</p> : messages.map((message) => <div key={message.id} className={message.type === "system" ? "rounded bg-ink p-3 text-center text-xs text-muted" : message.sender === self ? "ml-6" : "mr-6"}><p className="eyebrow">{message.sender === self ? "you" : message.sender}</p><p className="mt-1 rounded border border-line bg-ink p-3 text-sm">{message.text}</p></div>)}</div><form className="flex gap-2 border-t border-line p-3" onSubmit={onSend}><input className="field min-w-0" maxLength={280} value={value} onChange={(event) => setValue(event.target.value)} placeholder="message (1/sec)" /><button className="button button-primary px-3" aria-label="Send"><Send size={15} /></button></form></aside>;
const Loading = () => <section className="mx-auto flex min-h-[65vh] max-w-xl flex-col items-center justify-center text-center"><div className="spinner" /><p className="eyebrow mt-6">joining secure guest seat</p><p className="mt-3 text-muted">Syncing the room state…</p></section>;
const phaseLabel = (phase: string) => ({ LOBBY: "lobby", SETUP: "setup", READY: "ready check", REMATCH: "rematch lobby", COUNTDOWN: "countdown", QUESTION: "live question", REVEAL: "reveal", RESULTS: "results", PAUSED: "paused", FORFEIT: "forfeit", ABANDONED: "abandoned", EXPIRED: "expired" }[phase] ?? phase.toLowerCase());
const topicName = (id: string) => TOPICS.find((topic) => topic.id === id)?.label ?? id;
const typeLabel = (type: string) => ({ "multiple-choice": "selected response", numeric: "numeric", "short-answer": "short answer", "code-output": "C trace", "ordered-sequence": "ordered sequence" }[type] ?? type);
