import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, BookOpen, Check, Clock3, RotateCcw } from "lucide-react";
import { AppSettings } from "@/components/AppSettings";
import { connectSocket, socket } from "@/lib/socket";
import { TOPICS, type PublicQuestion, type TopicId } from "../../../shared/domain";

type SoloState = { phase: "QUESTION" | "RESULT" | "COMPLETE"; question: PublicQuestion | null; revealedQuestion: { answer: string | number | string[]; explanation: string; assumptions: string[] } | null; questionEndsAt: number | null; result: { correct: boolean; score: { total: number } } | null; runScore: number; runCorrect: number; runTotal: number };
const DEFAULT_TOPICS: TopicId[] = ["arrays-memory", "linked-lists", "stacks", "queues", "binary-trees", "sorting", "recursion", "analysis-mathematics"];
export default function Solo() {
  const [topics, setTopics] = useState<TopicId[]>(DEFAULT_TOPICS); const [state, setState] = useState<SoloState | null>(null); const [answer, setAnswer] = useState<string | string[]>(""); const [ordered, setOrdered] = useState<string[]>([]); const [now, setNow] = useState(() => Date.now()); const [error, setError] = useState("");
  useEffect(() => { const onState = (next: SoloState) => { setNow(Date.now()); setState(next); setAnswer(""); setOrdered([]); }; const onError = (payload: { message?: string }) => setError(payload.message ?? "Something went wrong."); socket.on("solo:state", onState); socket.on("server:error", onError); connectSocket(); return () => { socket.off("solo:state", onState); socket.off("server:error", onError); }; }, []);
  useEffect(() => { const id = window.setInterval(() => setNow(Date.now()), 500); return () => window.clearInterval(id); }, []);
  const start = () => { if (topics.length) socket.emit("solo:start", { topicIds: topics, count: 5, timerSeconds: 120 }); };
  const submit = () => { if (!state?.question) return; const value = state.question.type === "ordered-sequence" ? ordered : answer; socket.emit("solo:submit", { questionId: state.question.id, answer: value }); };
  const next = () => socket.emit("solo:next");
  if (!state) return <Shell><main className="mx-auto max-w-5xl px-5 py-14 sm:px-8"><Link to="/" className="inline-flex items-center gap-2 text-sm text-muted hover:text-gold"><ArrowLeft size={15} /> home</Link><section className="mt-14 max-w-2xl"><p className="eyebrow text-gold">same server grading engine</p><h1 className="display mt-3 text-6xl">solo practice.</h1><p className="mt-5 text-lg leading-8 text-muted">A current-run drill with original prompts, one locked answer per question, and the same 1,000 + 300 scoring model used in a match.</p><div className="mt-10 grid gap-2 sm:grid-cols-2">{TOPICS.map((topic) => <button key={topic.id} className={`topic-chip ${topics.includes(topic.id) ? "topic-chip-active" : ""}`} onClick={() => setTopics((current) => current.includes(topic.id) ? current.filter((item) => item !== topic.id) : [...current, topic.id])}>{topic.label}{topics.includes(topic.id) && <Check size={14} />}</button>)}</div><button className="button button-primary mt-7" onClick={start} disabled={!topics.length}><BookOpen size={16} /> start five-question run <ArrowRight size={16} /></button>{error && <p className="mt-4 text-sm text-red-300">{error}</p>}</section></main></Shell>;
  if (state.phase === "COMPLETE") return <Shell><main className="mx-auto max-w-2xl px-5 py-20 text-center"><p className="eyebrow text-gold">run complete</p><h1 className="display mt-3 text-6xl">good work.</h1><p className="mt-5 text-muted">{state.runCorrect}/{state.runTotal} correct · <span className="font-mono text-gold">{state.runScore.toLocaleString()}</span> points</p><div className="mt-8 flex justify-center gap-3"><button className="button button-primary" onClick={() => setState(null)}><RotateCcw size={16} /> new run</button><Link className="button button-ghost" to="/"><ArrowLeft size={16} /> home</Link></div></main></Shell>;
  const question = state.question; const seconds = state.questionEndsAt ? Math.max(0, Math.ceil((state.questionEndsAt - now) / 1000)) : 0;
  return <Shell><main className="mx-auto max-w-4xl px-5 py-8 sm:px-8"><div className="flex items-center justify-between"><Link to="/" className="inline-flex items-center gap-2 text-sm text-muted hover:text-gold"><ArrowLeft size={15} /> exit</Link><div className="font-mono text-sm text-muted">{state.runTotal + (state.phase === "QUESTION" ? 1 : 0)} / 5 · {state.runScore.toLocaleString()} pts</div></div>{state.phase === "RESULT" && state.revealedQuestion ? <section className="mx-auto mt-20 max-w-2xl text-center"><p className="eyebrow text-gold">answer reveal</p><h1 className="display mt-3 text-5xl">{state.result?.correct ? "correct" : "not quite"}</h1><p className="mt-8 rounded border border-gold/30 bg-gold/10 p-5 font-mono text-gold">{formatAnswer(state.revealedQuestion.answer)}</p><p className="mt-6 leading-7 text-muted">{state.revealedQuestion.explanation}</p><p className="mt-4 text-xs text-muted">Assumptions: {state.revealedQuestion.assumptions.join(" · ")}</p><button className="button button-primary mt-9" onClick={next}><ArrowRight size={16} /> next prompt</button></section> : question && <section className="mx-auto mt-12 max-w-3xl"><div className="flex items-center justify-between"><div><p className="eyebrow text-gold">solo prompt</p><p className="mt-1 text-sm text-muted">{topicName(question.topicId)} · {question.difficulty}</p></div><span className="timer"><Clock3 size={16} />{seconds}s</span></div><article className="panel mt-8 p-6 sm:p-9"><h1 className="text-2xl font-semibold leading-snug sm:text-4xl">{question.prompt}</h1><SoloControl question={question} answer={answer} setAnswer={setAnswer} ordered={ordered} setOrdered={setOrdered} /><button className="button button-primary mt-8 w-full" onClick={submit} disabled={!hasAnswer(question, answer, ordered)}><Check size={16} /> submit once</button></article></section>}</main></Shell>;
}
const SoloControl = ({ question, answer, setAnswer, ordered, setOrdered }: { question: PublicQuestion; answer: string | string[]; setAnswer: (answer: string) => void; ordered: string[]; setOrdered: (items: string[]) => void }) => { if (question.type === "multiple-choice") return <div className="mt-8 grid gap-3">{question.options?.map((option) => <button key={option.id} className={`answer-option ${answer === option.id ? "answer-option-active" : ""}`} onClick={() => setAnswer(option.id)}><span className="option-key">{option.id}</span>{option.label}</button>)}</div>; if (question.type === "ordered-sequence") return <div className="mt-8 grid gap-2">{question.items?.map((item) => <button key={item.id} className={`answer-option ${ordered.includes(item.id) ? "opacity-40" : ""}`} disabled={ordered.includes(item.id)} onClick={() => setOrdered([...ordered, item.id])}><span className="option-key">{ordered.indexOf(item.id) + 1 || "·"}</span>{item.label}</button>)}</div>; return <textarea className="field mt-8 min-h-28 font-mono" value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder={question.type === "numeric" ? "enter a number" : "type your answer"} />; };
const hasAnswer = (question: PublicQuestion, answer: string | string[], ordered: string[]) => question.type === "ordered-sequence" ? ordered.length === (question.orderLength ?? question.items?.length ?? 0) : String(answer).trim().length > 0;
const formatAnswer = (answer: string | number | string[]) => Array.isArray(answer) ? answer.join(" → ") : String(answer);
const topicName = (id: string) => TOPICS.find((topic) => topic.id === id)?.label ?? id;
const Shell = ({ children }: { children: React.ReactNode }) => <div className="min-h-screen bg-ink text-cream"><header className="mx-auto flex max-w-7xl items-center justify-between border-b border-line px-5 py-5 sm:px-8"><Link to="/" className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded bg-gold font-black text-ink">FE</span><span className="font-mono text-sm font-bold tracking-[.18em]">ARENA</span></Link><AppSettings /></header>{children}</div>;
